package org.senda.browser.ui.components

// Generated by scripts/build_wallpapers.py: do not edit by hand.

/** Size and SHA-256 of each optimized wallpaper; the ones not in [BUNDLED] are downloaded from [RELEASE]. */
internal object WallpaperDownloads {
    const val RELEASE = "wallpapers-1"
    val BUNDLED = setOf("debian_ceratopsian", "debian_ceratopsian_portrait", "arch_conference", "xfce_stripes", "gnu_wilgus_gnutiling", "gnome_adwaita")

    class File(val bytes: Long, val sha256: String)

    val files = mapOf(
        "arch_archbtw" to File(132678L, "9233719cd66aee074d8caa22cc0f264369bfd56ad87c16261bb526a0c1037935"),
        "arch_archwave" to File(247420L, "5f9df346680dd1be71d7fd5cca0c780b5093198377970356885c0285185955eb"),
        "arch_archwaveinv" to File(354184L, "82e8014002e56e1c8ff193dfe0eb6e70237bd83743e94560405d44b0f11e43b3"),
        "arch_awesome" to File(170284L, "d626b1dbec9164d3a37b109aa3549ac9c466858bfec2f68929c8c6ccc4351666"),
        "arch_conference" to File(39900L, "e110873cb3ca909299b06f6d7e6d9d98065e41529f3cffa47b7394f5009c0425"),
        "arch_geolanes" to File(1307426L, "efea93665b66c4c606d96362b5951e73625641bba73863d2d8a4fcff2022d485"),
        "arch_geowaves" to File(1521034L, "c84803f24aa70185bf4a49b948d2385ca3b45743fb98dc11bfb71b2df060d226"),
        "arch_gritty" to File(3022138L, "7633c4db8f799fbe1d87e97c20dcdcb195dc91a7232b5ca8675f09b4518cae00"),
        "arch_simple" to File(35048L, "25ac71dcc0611d9e5f6389d95adb193e9f99bafe4c25115bb564f98c44d22887"),
        "arch_split" to File(24506L, "5c66cc318ee84f7cb5844bbeba5631cbdb8c50084c09906fba527b3f9c403334"),
        "arch_wave" to File(428030L, "640c4d922d3bdab4a3787bd4200f3e3d9c12c788b6321e68ac9c01a6419f03bf"),
        "arch_wirefeather" to File(2157530L, "75173ab10aedb23b8f3b5a68eca9d132b0beef2f0aa69831a01c02aa22fb210b"),
        "arch_wireparts" to File(237176L, "3d097ec544afe04d71a4b09531cee62390c199ac1cba6531fb4d3490d8b262f1"),
        "debian_ceratopsian" to File(39110L, "4ec41104bf8407bb4cd6f02cc61408dd22fe169820d1bd514e115fc7b3e993c1"),
        "debian_ceratopsian_portrait" to File(44636L, "fc4706a6db081df88673dd86920c9cc562dd8a0db35905c4bd4db6904335317c"),
        "debian_emerald" to File(76100L, "7d5db5f1151f09356c3dbbc6389608137b2cf550a68761e825a4859417e485dd"),
        "debian_futureprototype" to File(39490L, "02af2bf3f3d9c5c130990da0ed6ed20d230ab523ae67a9eda220928773974834"),
        "debian_homeworld" to File(40270L, "923b6ddb91a42d30a42e0f93a86564aa4d4ca791eb9ef66ceda3b3762921f3cc"),
        "debian_joy" to File(77864L, "d5779d117a47be5e6c4ccb60e0158986cc590185c047402a1e517edb3dffd5cc"),
        "debian_lines" to File(75606L, "6fb7305ee8767114d5cc21b8a1526be4143a43cc78ebc2f1f8467eb0be802db5"),
        "debian_moonlight" to File(47922L, "d6fdb3f5de3155f8ceb746a1e27ef9bcb195cbd3baaeef8ce71d54e4858176c5"),
        "debian_softwaves" to File(117958L, "16c01fcd147de766fd67c94ca90724d6262d3aa15ecf118a3826cf4d544b4553"),
        "debian_spacefun" to File(113684L, "42d674fc397bec7bdfb326dac8f8cdcf4d47b73efd3f06abe69663e0aaaf715e"),
        "fedora_f38" to File(941320L, "f02da6f63b3c81068ea3dad812213c82a63e7566b77581baef4810b5e625d19c"),
        "fedora_f39" to File(2249774L, "671a73b7749c99939f1e351db2ca1a853e014087fa0b5639743fb59e83327e87"),
        "fedora_f40" to File(611828L, "42156f445f0226e8d6cdfc722b0da3d70c3b4002dfda22204e3d7eb55cfcb4d9"),
        "fedora_f41" to File(1957430L, "8c5476652712373e3a40d2b5c06fc6171252159e3b73f490bbbc10c33c017fdd"),
        "fedora_f42" to File(446784L, "1bbb66cafd1be062de3e014f38db6707539b021bf2a8ca5391c844c5a84c9749"),
        "fedora_f43" to File(401328L, "958c4be5ca9894b4e335631b0f2fbd7fbe93c628a35db36c534b4b1e9241bca9"),
        "gentoo_abducted" to File(23576L, "6116fac424aab7d9eac4bb735aa709395feab99725b50f269a513e8981bbbf07"),
        "gentoo_cow" to File(35778L, "05714696e0e7332e7da367242fad25ba36cb033bc98e2fabca3a1e0d3a4b1005"),
        "gentoo_g10_blue" to File(458206L, "71ff298ff08404c863acb5ae90bd3f89efe5d4f6ba821c5b72a568149842321e"),
        "gentoo_g10_purple" to File(436638L, "1a019809d6953397b29292cb7d323f081766577e62c3f34c6d49fabdebdccba5"),
        "gentoo_larry" to File(137560L, "5a6d510a31c4820c1f1ac24e53dbc399720d0a62c7e6b97d7ee9758a7bebbd55"),
        "gnome_adwaita" to File(107162L, "e3748bede637a5dd84b8c8ff15590c204324ec53d4927062f9f0053ac38d864a"),
        "gnome_amber" to File(2068958L, "2ff612bf843e31ae3bf5ac23223e3c476f9252dc35318136ac4fef700abd561f"),
        "gnome_blobs" to File(75224L, "1539da627ded3847d8dab3bf10565bc6e44f65669376bbf31ac1bd6999262795"),
        "gnome_ditheredsun" to File(526640L, "d185df477005da444cfcc2a9b86d48bf0aec870ce68e137ab1180527aa9dc804"),
        "gnome_fold" to File(2723834L, "332c761a8f34d1d0248c80cecba9fcd5fbc24713ff98923590870f938922c6d0"),
        "gnome_map" to File(123342L, "0b5c3a0120dc539ad375bbb9a3d634b5e3ad71273122339531e21b8231ed10c0"),
        "gnu_free_your_soul" to File(141614L, "157468143aa02cab9c088229b31f9ad47f4a8135b964c8fc989b0612c94660c2"),
        "gnu_skwid_free_side" to File(154742L, "a19a266b40f8f287703de665e27a3d851b6e82c0e77ed484c4a42fedc9e21148"),
        "gnu_skwid_fsfs" to File(76332L, "6e0274f7ba378bb1b4e13b537d9c2d6839f4ace936912b2e2f8455779d42402d"),
        "gnu_skwid_gnu_fsf" to File(692360L, "3995e4772f6924771691873a586b494408bd081fffb7f13ceb659644e4c5ac8b"),
        "gnu_skwid_hurd" to File(951174L, "9ff9e7696a9115077fbdfe459276e1b6aa0202ec7e272eb24cb936a9e7f0c5a8"),
        "gnu_this_is_freedom" to File(449138L, "881d02d5038101a6435a952f916aba10e14ffa554e680ffe0c3e379a949a1a2e"),
        "gnu_wilgus_gnutiling" to File(534372L, "6a63bbff802864c94d55f9968baeb5c3229d8bd1572895d3c5482bb97418262d"),
        "kde_altai" to File(157072L, "d8c6bf4a9825be71d167442f387807c5ad6528a2215c1e7dc685909947fa0443"),
        "kde_elarun" to File(76392L, "6b239119c8f6c9b8d5966b1d75694eedb630f153ee2147a12f815020a58b978d"),
        "kde_flyingkonqui" to File(67034L, "95fdd8adb13444fda9ec39c9ff1f0e7d88bc0415f5709326ae0f9c725646ff4d"),
        "kde_honeywave" to File(403972L, "8e247e36f418410a40ef57defe95233cd4fa469851ca9068a0cf53ebed9f8821"),
        "kde_kokkini" to File(239680L, "e87de7adadbe58b650562964e5e770ac2497947aaba581d85840ec1545bbfa1d"),
        "kde_milkyway" to File(347048L, "df49170c9597d21511986933af9a64e1c16f80b60df57858cf4a4d3b7c4b6409"),
        "kde_mountain" to File(191948L, "9844e2086fd3dde858bde4e8b88a770061b6d55e3838fb600102f13104e0f202"),
        "kde_volna" to File(1100910L, "12d306427dfe106a261458cce5d516d998a3422050d98b3d183780c6b41af3f1"),
        "xfce_cp_dark" to File(82174L, "8d394fd1413823093e284d96af6738d38faa045a51ff5fa283d724fb06a71c9a"),
        "xfce_flower" to File(63016L, "82179d09533ea1ff072aeea10609c798b083c13b355d616b451253ff8fb955ca"),
        "xfce_leaves" to File(119236L, "0684b0716dd36844b56ddb2271fab94bb5906bbd188d146e530678d05f6ce386"),
        "xfce_light" to File(291770L, "e5b3cd28ab5cb87b5c6688f0ca934b1d9bac0760a22e03fbcb5b4d51ba5f4fba"),
        "xfce_mouserace" to File(58824L, "acf5c2a01e42f93066e1c249d78bcd13f46d4b7712de6a27a0a36484423bfdef"),
        "xfce_shapes" to File(738904L, "28dd08e1434c9c71bcdcce231e0fd55404cec8e145b667dea15a56354f5b7ac8"),
        "xfce_stripes" to File(36138L, "648103d87d4a751405b42031c8456b00e7141151d36a93557b80a699206894ae"),
        "xfce_teal" to File(50870L, "35f8ab0e3ac59b350f3d553212e39dc859b81ff3af5ee363379aa31680aa0a64"),
        "xfce_verticals" to File(40584L, "fb23f551273927b4a87fd49801013b0b35020649fff483c3286bd2d63e7f90ba"),
        "xfce_x" to File(68330L, "94798b7ae99e66a3ff634bd04a51a959a1ab2d83e36087595baad521262dd614")
    )
}
