#!/usr/bin/env python3
"""Builds the wallpapers Senda ships and downloads.

From the originals in wallpapers/original (up to 5120 px):
  1. Writes optimized copies (long side <= 3840 px, WebP q94 keeping the grain, so gradients do not band)
     to build/wallpapers-release/. These are uploaded as assets of the release WALLPAPER_RELEASE.
  2. Copies the BUNDLED ones into app/src/main/assets/wallpapers/ (they go inside the APK).
  3. Writes WallpaperDownloads.kt with the size and SHA-256 of every file: Senda rejects a download
     whose hash does not match.

Requires cwebp, dwebp and webpinfo (libwebp). Usage: scripts/build_wallpapers.py
"""
import hashlib
import pathlib
import shutil
import subprocess
import sys
import tempfile

ROOT = pathlib.Path(__file__).resolve().parent.parent
ORIGINALS = ROOT / "wallpapers" / "original"
OUT = ROOT / "build" / "wallpapers-release"
ASSETS = ROOT / "app" / "src" / "main" / "assets" / "wallpapers"
KOTLIN = ROOT / "app" / "src" / "main" / "java" / "org" / "senda" / "browser" / "ui" / "components" / "WallpaperDownloads.kt"

WALLPAPER_RELEASE = "wallpapers-1"
MAX_SIDE = 3840
# Light ones that work in portrait and landscape, one per family where possible (plus the official portrait
# version of the default one): the rest are downloaded when chosen
BUNDLED = ["debian_ceratopsian", "debian_ceratopsian_portrait", "arch_conference", "xfce_stripes", "gnu_wilgus_gnutiling", "gnome_adwaita"]


def size_of(path):
    info = subprocess.run(["webpinfo", "-summary", str(path)], capture_output=True, text=True, check=True).stdout
    w = h = None
    for line in info.splitlines():
        line = line.strip()
        if line.startswith("Width:") and w is None:
            w = int(line.split()[1])
        elif line.startswith("Height:") and h is None:
            h = int(line.split()[1])
    return w, h


def optimize(src, dst, tmp):
    w, h = size_of(src)
    resize = []
    if max(w, h) > MAX_SIDE:
        resize = ["-resize", str(MAX_SIDE), "0"] if w >= h else ["-resize", "0", str(MAX_SIDE)]
    png = tmp / "t.png"
    subprocess.run(["dwebp", "-quiet", str(src), "-o", str(png)], check=True)
    subprocess.run(["cwebp", "-quiet", "-q", "94", "-m", "6", "-sharp_yuv", "-sns", "0", "-f", "0",
                    "-metadata", "none", *resize, str(png), "-o", str(dst)], check=True)
    # Never larger than the original (some are already small)
    if dst.stat().st_size > src.stat().st_size:
        shutil.copyfile(src, dst)


def main():
    originals = sorted(ORIGINALS.glob("*.webp"))
    if not originals:
        sys.exit("No originals in " + str(ORIGINALS))
    OUT.mkdir(parents=True, exist_ok=True)
    rows = []
    with tempfile.TemporaryDirectory() as t:
        for src in originals:
            dst = OUT / src.name
            optimize(src, dst, pathlib.Path(t))
            data = dst.read_bytes()
            rows.append((src.stem, len(data), hashlib.sha256(data).hexdigest()))
            print(f"{src.stem}: {len(data)} bytes")
    for old in ASSETS.glob("*.webp"):
        old.unlink()
    for wid in BUNDLED:
        shutil.copyfile(OUT / f"{wid}.webp", ASSETS / f"{wid}.webp")
    lines = [
        "package org.senda.browser.ui.components",
        "",
        "// Generated by scripts/build_wallpapers.py: do not edit by hand.",
        "",
        "/** Size and SHA-256 of each optimized wallpaper; the ones not in [BUNDLED] are downloaded from [RELEASE]. */",
        "internal object WallpaperDownloads {",
        f'    const val RELEASE = "{WALLPAPER_RELEASE}"',
        "    val BUNDLED = setOf(" + ", ".join(f'"{b}"' for b in BUNDLED) + ")",
        "",
        "    class File(val bytes: Long, val sha256: String)",
        "",
        "    val files = mapOf(",
    ]
    lines += [f'        "{wid}" to File({size}L, "{sha}"),' for wid, size, sha in rows]
    lines[-1] = lines[-1].rstrip(",")
    lines += ["    )", "}", ""]
    KOTLIN.write_text("\n".join(lines))
    total = sum(r[1] for r in rows)
    bundled = sum(r[1] for r in rows if r[0] in BUNDLED)
    print(f"Total {total} bytes; bundled {bundled} bytes; manifest {KOTLIN.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
